services:
    metamanager:
        image: docker.io/fackop/pppackage-metamanager:latest
        user: $USER
        command:
            - /mnt/root/
            - --config
            - /mnt/config.json
        environment:
            HOST_PWD: $PWD
        volumes:
            - type: bind
              source: $PWD/root/
              target: /mnt/root/

            - type: bind
              source: $PWD/output/
              target: /mnt/output/

            - type: bind
              source: $PWD/.github/config.json
              target: /mnt/config.json

            - type: bind
              source: $XDG_RUNTIME_DIR/podman/podman.sock
              target: /run/podman/podman.sock

            - type: bind
              source: $PWD/cache/
              target: /mnt/cache/

            - type: bind
              source: /tmp/
              target: /tmp/

            - type: bind
              source: /home/runner/
              target: /root/

            - type: bind
              source: /etc/passwd
              target: /etc/passwd
              read_only: true
            - type: bind
              source: /etc/group
              target: /etc/group
              read_only: true
