services:
    metamanager:
        image: docker.io/fackop/pppackage-metamanager:latest
        user: $USER
        command:
            - /mnt/root/
            - --config
            - /mnt/config.json
        environment:
            WORKING_DIRECTORY: $PWD
        volumes:
            - type: bind
              source: $PWD/root/
              target: /mnt/root/

            - type: bind
              source: $PWD/output/
              target: /mnt/output/

            - type: bind
              source: $PWD/.github/config.json
              target: /mnt/config.json

            - type: bind
              source: $XDG_RUNTIME_DIR/podman/podman.sock
              target: /run/podman/podman.sock

            - type: bind
              source: $PWD/cache/
              target: /mnt/cache/

            - type: bind
              source: $PWD/workdir/
              target: /mnt/workdir/

            - type: bind
              source: $PWD/database/archlinux-core/
              target: /mnt/repositories/database/archlinux-core/
            - type: bind
              source: $PWD/database/archlinux-extra/
              target: /mnt/repositories/database/archlinux-extra/
            - type: bind
              source: $PWD/database/AUR/
              target: /mnt/repositories/database/AUR/
            - type: bind
              source: $PWD/database/conancenter/
              target: /mnt/repositories/database/conancenter/

            - type: bind
              source: /etc/passwd
              target: /etc/passwd
              read_only: true
            - type: bind
              source: /etc/group
              target: /etc/group
              read_only: true
