name: pppackage
services:
    archlinux-core:
        image: docker.io/fackop/pppackage-repository-driver-pacman:latest
        healthcheck:
            test: ["CMD", "curl", "http://localhost:8888"]
        command:
            - 0.0.0.0:8888
        environment:
            CONFIG_PATH: /mnt/config.json
        ports:
            - 8888
        volumes:
            - type: bind
              source: $CONFIG_ARCHLINUX_CORE
              target: /mnt/config.json
            - type: volume
              source: database-archlinux-core
              target: /mnt/database/
    archlinux-extra:
        image: docker.io/fackop/pppackage-repository-driver-pacman:latest
        healthcheck:
            test: ["CMD", "curl", "http://localhost:8888"]
        command:
            - 0.0.0.0:8888
        environment:
            CONFIG_PATH: /mnt/config.json
        ports:
            - 8888
        volumes:
            - type: bind
              source: $CONFIG_ARCHLINUX_EXTRA
              target: /mnt/config.json
            - type: volume
              source: database-archlinux-extra
              target: /mnt/database/
    aur:
        image: docker.io/fackop/pppackage-repository-driver-aur:latest
        healthcheck:
            test: ["CMD", "curl", "http://localhost:8888"]
        command:
            - 0.0.0.0:8888
        environment:
            CONFIG_PATH: /mnt/config.json
        ports:
            - 8888
        volumes:
            - type: bind
              source: $CONFIG_AUR
              target: /mnt/config.json
    conancenter:
        image: docker.io/fackop/pppackage-repository-driver-conan:latest
        healthcheck:
            test: ["CMD", "curl", "http://localhost:8888"]
        command:
            - 0.0.0.0:8888
        environment:
            CONFIG_PATH: /mnt/config.json
        ports:
            - 8888
        volumes:
            - type: bind
              source: $CONFIG_CONANCENTER
              target: /mnt/config.json
            - type: volume
              source: cache-conancenter
              target: /mnt/cache/
    metamanager:
        image: docker.io/fackop/pppackage-metamanager:latest
        depends_on:
            archlinux-core:
                condition: service_healthy
            archlinux-extra:
                condition: service_healthy
            aur:
                condition: service_healthy
            conancenter:
                condition: service_healthy
        command:
            - /mnt/root/
            - --config
            - /mnt/config.json
            - --generators
            - /mnt/output/generators
            - --graph
            - /mnt/output/graph.dot
        volumes:
            - type: bind
              source: $ROOT
              target: /mnt/root/
            - type: bind
              source: $OUTPUT
              target: /mnt/output
            - type: bind
              source: $CONFIG_PATH
              target: /mnt/config.json
            - type: bind
              source: $XDG_RUNTIME_DIR/podman/podman.sock
              target: /run/podman/podman.sock
volumes:
    database-archlinux-core:
    database-archlinux-extra:

    cache-conancenter:
