name: pppackage
services:
    metamanager:
        image: docker.io/fackop/pppackage-metamanager:latest
        command:
            - /mnt/root/
            - --config
            - /mnt/config.json
            - --generators
            - /mnt/output/generators/
            - --graph
            - /mnt/output/graph.dot
        environment:
            HOST_PWD: $PWD
        volumes:
            - type: bind
              source: $PWD/tmp/root/
              target: /mnt/root/

            - type: bind
              source: $PWD/tmp/output/
              target: /mnt/output/

            - type: bind
              source: $PWD/examples/metamanager/containerized/config.json
              target: /mnt/config.json

            - type: bind
              source: $XDG_RUNTIME_DIR/podman/podman.sock
              target: /run/podman/podman.sock

            - type: bind
              source: /tmp/
              target: /tmp/

            - type: volume
              source: home
              target: /root/
volumes:
    home:
        external: true
        name: $PPPACKAGE_HOME
