name: pppackage
services:
    metamanager:
        image: docker.io/fackop/pppackage-metamanager:latest
        command:
            - /mnt/root/
            - --config
            - /mnt/config.json
            - --generators
            - /mnt/output/generators/
            - --graph
            - /mnt/output/graph.dot
        volumes:
            - type: bind
              source: $PWD/tmp/root/
              target: /mnt/root/

            - type: bind
              source: $PWD/tmp/output/
              target: /mnt/output

            - type: bind
              source: $PWD/examples/metamanager/containerized/config.json
              target: /mnt/config.json

            - type: bind
              source: $XDG_RUNTIME_DIR/podman/podman.sock
              target: /run/podman/podman.sock

            - type: bind
              source: $PWD/tmp/cache/
              target: /mnt/cache/

            - type: bind
              source: /tmp
              target: /mnt/workdir/

            - type: bind
              source: $PWD/tmp/database/archlinux-core/
              target: /mnt/repository/database/archlinux-core/
            - type: bind
              source: $PWD/tmp/database/archlinux-extra/
              target: /mnt/repository/database/archlinux-extra/
            - type: bind
              source: $PWD/tmp/database/AUR/
              target: /mnt/repository/database/AUR/
            - type: bind
              source: $PWD/tmp/database/conancenter/
              target: /mnt/repository/database/conancenter/
