name: Push

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1

            - uses: gacts/install-podman@v1.1.0

            - name: Download seccomp.json
              run: sudo wget https://raw.githubusercontent.com/containers/common/main/pkg/seccomp/seccomp.json --output-document /etc/containers/seccomp.json

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Login to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push pppackage-metamanager
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: metamanager
                  push: true
                  tags: docker.io/fackop/pppackage-metamanager:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Push pppackage-repository-driver-pacman
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-pacman
                  push: true
                  tags: docker.io/fackop/repository-driver-pacman:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Push pppackage-repository-driver-aur
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-aur
                  push: true
                  tags: docker.io/fackop/repository-driver-aur:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Push pppackage-repository-driver-conan
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-conan
                  push: true
                  tags: docker.io/fackop/repository-driver-conan:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Push pppackage-repository-driver-pp
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-pp
                  push: true
                  tags: docker.io/fackop/repository-driver-pp:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
