name: Push

on:
    push:
        branches:
            - main

jobs:
    build-metamanager:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: metamanager
                  push: true
                  tags: docker.io/fackop/pppackage-metamanager:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    build-solver:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: solver
                  push: true
                  tags: docker.io/fackop/pppackage-solver:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    build-updater:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: updater
                  push: true
                  tags: docker.io/fackop/pppackage-updater:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    build-repo-pacman:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: repository-driver-pacman
                  push: true
                  tags: docker.io/fackop/pppackage-repository-driver-pacman:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    build-repo-aur:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: repository-driver-aur
                  push: true
                  tags: docker.io/fackop/pppackage-repository-driver-aur:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    build-repo-conan:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: repository-driver-conan
                  push: true
                  tags: docker.io/fackop/pppackage-repository-driver-conan:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    build-repo-pp:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/setup-buildx-action@v3.0.0

            - uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v5.3.0
              with:
                  target: repository-driver-pp
                  push: true
                  tags: docker.io/fackop/pppackage-repository-driver-pp:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
