name: Push

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Login to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push pppackage
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: metamanager
                  push: true
                  tags: fackop/pppackage:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
