name: Push

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1

            - uses: gacts/install-podman@v1.1.0

            - name: Cache arch
              uses: actions/cache@v3.3.3
              with:
                  path: ${{ github.workspace }}/cache/arch
                  key: cache-arch

            - name: Cache Conan
              uses: actions/cache@v3.3.3
              with:
                  path: ${{ github.workspace }}/cache/conan
                  key: cache-conan

            - name: Cache PP
              uses: actions/cache@v3.3.3
              with:
                  path: ${{ github.workspace }}/cache/PP
                  key: cache-PP

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Login to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push pppackage
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: metamanager
                  load: true
                  tags: docker.io/fackop/pppackage:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Run PPpackage
              run: |
                  mkdir -p cache/arch cache/conan cache/PP
                  USER="$(id -u):$(id -g)" docker compose --file .github/compose.yaml run --rm -T metamanager < input/basic.json

            - name: Build and push pppackage-submanager-db-init
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: submanager-db-init
                  push: true
                  tags: docker.io/fackop/pppackage-submanager-db-init:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push pppackage-submanager-create-user
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: submanager-create-user
                  push: true
                  tags: docker.io/fackop/pppackage-submanager-create-user:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push pppackage-arch
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: submanager-arch
                  push: true
                  tags: docker.io/fackop/pppackage-arch:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push pppackage-conan
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: submanager-conan
                  push: true
                  tags: docker.io/fackop/pppackage-conan:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push pppackage-pp
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: submanager-pp
                  push: true
                  tags: docker.io/fackop/pppackage-pp:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push pppackage
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: metamanager
                  push: true
                  tags: docker.io/fackop/pppackage:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
