name: Test

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1

            - uses: gacts/install-podman@v1.1.0

            - name: Download seccomp.json
              run: sudo wget https://raw.githubusercontent.com/containers/common/main/pkg/seccomp/seccomp.json --output-document /etc/containers/seccomp.json

            - name: Cache products
              uses: actions/cache@v4.0.2
              with:
                  path: ${{ github.workspace }}/cache/product
                  key: cache-products

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Build pppackage-metamanager
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: metamanager
                  load: true
                  tags: docker.io/fackop/pppackage-metamanager:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Run PPpackage
              run: |
                  mkdir -p root/ output/ cache/product/ cache/repository/conan/ cache/repository/PP/ database/archlinux-core/ database/archlinux-extra/ database/PP/
                  USER="$(id -u):$(id -g)" docker compose --file .github/compose.yaml run --rm -T metamanager < examples/input/basic.json

            # - name: See if ldconfig ran
            #   run: ls -l root/etc/ld.so.cache

            - name: Build pppackage-repository-driver-pacman
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-pacman
                  tags: docker.io/fackop/repository-driver-pacman:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build pppackage-repository-driver-aur
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-aur
                  tags: docker.io/fackop/repository-driver-aur:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build pppackage-repository-driver-conan
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-conan
                  tags: docker.io/fackop/repository-driver-conan:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build pppackage-repository-driver-pp
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: repository-driver-pp
                  tags: docker.io/fackop/repository-driver-pp:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
