name: Test

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1

            - uses: gacts/install-podman@v1.1.0

            - name: Cache arch
              uses: actions/cache@v3.3.3
              with:
                  path: ${{ github.workspace }}/cache/arch
                  key: cache-arch

            - name: Cache Conan
              uses: actions/cache@v3.3.3
              with:
                  path: ${{ github.workspace }}/cache/conan
                  key: cache-conan

            - name: Cache PP
              uses: actions/cache@v3.3.3
              with:
                  path: ${{ github.workspace }}/cache/PP
                  key: cache-PP

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Build and push pppackage
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  tags: pppackage:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Run PPpackage
              run: |
                  mkdir -p cache/arch cache/conan cache/PP
                  USER="$(id -u):$(id -g)" docker compose --file .github/compose.yaml run --build --rm -T metamanager < input/basic.json

            - name: See if ldconfig ran
              run: ls -l root/etc/ld.so.cache
