name: Test

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Start podman API service
              run: |
                  systemctl --user enable --now podman

            - name: Run PPpackage
              run: |
                  USER="$(id -u):$(id -g)" WORKDIR=$(pwd) docker compose --file compose-docker.yaml run --build --rm -T metamanager < input/basic.json

            - name: See if ldconfig ran
              run: ls -l root/etc/ld.so.cache
