name: Test

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1

            - uses: gacts/install-podman@v1.1.0

            - name: Download seccomp.json
              run: sudo wget https://raw.githubusercontent.com/containers/common/main/pkg/seccomp/seccomp.json --output-document /etc/containers/seccomp.json

            - name: Cache arch
              uses: actions/cache@v4.0.2
              with:
                  path: ${{ github.workspace }}/cache/arch
                  key: cache-arch

            - name: Cache Conan
              uses: actions/cache@v4.0.2
              with:
                  path: ${{ github.workspace }}/cache/conan
                  key: cache-conan

            - name: Cache PP
              uses: actions/cache@v4.0.2
              with:
                  path: ${{ github.workspace }}/cache/PP
                  key: cache-PP

            - name: Cache AUR
              uses: actions/cache@v4.0.2
              with:
                  path: ${{ github.workspace }}/cache/AUR
                  key: cache-AUR

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Build and push pppackage
              uses: docker/build-push-action@v5.1.0
              with:
                  context: ${{ github.workspace }}
                  target: metamanager
                  load: true
                  tags: docker.io/fackop/pppackage-metamanager:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Run PPpackage
              run: |
                  mkdir -p root/ output/ cache/conan cache/PP database/archlinux-core database/archlinux-extra database/PP
                  USER="$(id -u):$(id -g)" docker compose --file .github/compose.yaml run --rm -T metamanager < examples/input/basic.json

            # - name: See if ldconfig ran
            #   run: ls -l root/etc/ld.so.cache
