name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        version: 1
        packages: runc
    - name: Test runc
      run: |
        docker run fackop/runc runc
