name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Package cache
      uses: actions/cache@v3.3.2
      with:
        path: ${{ github.workspace }}/cache
        key: package-cache

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build and push fackop/pppackage
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/images/PPpackage/Dockerfile
        push: ${{ github.ref_name == 'main' }}
        tags: fackop/pppackage:latest
        outputs: type=${{ github.ref_name == 'main' && 'image' || 'docker' }}
        cache-from: type=registry,ref=fackop/pppackage:buildcache
        cache-to: type=registry,ref=fackop/pppackage:buildcache,mode=max

    - name: Build and push fackop/pppackage-runner
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/images/PPpackage-runner/Dockerfile
        push: ${{ github.ref_name == 'main' }}
        tags: fackop/pppackage-runner:latest
        outputs: type=${{ github.ref_name == 'main' && 'image' || 'docker' }}
        cache-from: type=registry,ref=fackop/pppackage-runner:buildcache
        cache-to: type=registry,ref=fackop/pppackage-runner:buildcache,mode=max

    - name: Try run.sh
      run: ./run.sh docker ${{ github.workspace }}/cache "$(pwd)/generators" "$(pwd)/root" --debug <input/basic.json

    - name: See if ldconfig ran
      run: ls -l root/etc/ld.so.cache
