name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push fackop/pppackage
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/images/PPpackage/Dockerfile
        push: true
        tags: fackop/pppackage

    - name: Build and push fackop/pppackage-runc
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/images/PPpackage-runc/Dockerfile
        push: true
        tags: fackop/pppackage-runc

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/tmp/cache
        key: cache

    - name: Try run.sh
      run: ./run.sh tmp/ <tmp/input/input-basic.json

    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: ${{ github.workspace }}/tmp/cache
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}

    - name: See if ldconfig ran
      run: ls -l tmp/PPpackage-runc/containers/$(docker run --rm fackop/pppackage head --lines=1 /etc/machine-id)/root/etc/ld.so.cache
