name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        version: 1
        packages: runc skopeo umoci
    - name: Fetch image
      run: |
        skopeo copy docker://archlinux:latest oci:archlinux:latest
    - name: Unpack image
      run: |
        umoci unpack --rootless --image archlinux archlinux-bundle
    - name: Run image
      run: |
        runc run --bundle archlinux-bundle container
