name: Test

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: python3 python3-venv python-is-python3
                  version: 1.0

            - name: Set up Python 3.11
              uses: actions/setup-python@v4.7.1
              with:
                  python-version: "3.11"

            - name: Package cache
              uses: actions/cache@v3.3.2
              with:
                  path: ${{ github.workspace }}/cache
                  key: package-cache

            - name: Log in to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Build and push fackop/pppackage-pp
              uses: docker/build-push-action@v5.0.0
              with:
                  context: ${{ github.workspace }}
                  file: ${{ github.workspace }}/images/PPpackage-PP/Dockerfile
                  push: ${{ github.ref_name == 'main' }}
                  tags: fackop/pppackage-pp:latest
                  outputs: type=${{ github.ref_name == 'main' && 'image' || 'docker' }}
                  cache-from: type=registry,ref=fackop/pppackage-pp:buildcache
                  cache-to: type=registry,ref=fackop/pppackage-pp:buildcache,mode=max

            - name: Build and push fackop/pppackage-arch
              uses: docker/build-push-action@v5.0.0
              with:
                  context: ${{ github.workspace }}
                  file: ${{ github.workspace }}/images/PPpackage-arch/Dockerfile
                  push: ${{ github.ref_name == 'main' }}
                  tags: fackop/pppackage-arch:latest
                  outputs: type=${{ github.ref_name == 'main' && 'image' || 'docker' }}
                  cache-from: type=registry,ref=fackop/pppackage-arch:buildcache
                  cache-to: type=registry,ref=fackop/pppackage-arch:buildcache,mode=max

            - name: Build and push fackop/pppackage-conan
              uses: docker/build-push-action@v5.0.0
              with:
                  context: ${{ github.workspace }}
                  file: ${{ github.workspace }}/images/PPpackage-conan/Dockerfile
                  push: ${{ github.ref_name == 'main' }}
                  tags: fackop/pppackage-conan:latest
                  outputs: type=${{ github.ref_name == 'main' && 'image' || 'docker' }}
                  cache-from: type=registry,ref=fackop/pppackage-conan:buildcache
                  cache-to: type=registry,ref=fackop/pppackage-conan:buildcache,mode=max

            - name: Try run.sh
              run: |
                  python -m venv .venv/
                  source .venv/bin/activate
                  pip install -r requirements.txt
                  python -m PPpackage_run docker --debug --wait-max-retries ${{ github.ref_name == 'main' && 1000 || 10 }} ${{ github.workspace }}/cache "$(pwd)/generators" "$(pwd)/root" < input/basic.json

            - name: See if ldconfig ran
              run: ls -l root/etc/ld.so.cache
